import React from "react";

export default function File(props) {
  return (
    <div className="flex flex-col absolute w-full h-full top-0 z-20 lg:top-2/4 lg:left-2/4 lg:transform lg:-translate-x-2/4 lg:-translate-y-2/4 lg:w-3/4 lg:h-3/4 lg:rounded-lg lg:border-[0.5px] lg:border-gray-400">
      <div className="hidden lg:flex justify-between items-center bg-[#3F3837] rounded-tr-lg rounded-tl-lg w-full">
        <div className="flex flex-row m-2 bg-[#3F3837]">
          <div className="w-4 h-4 rounded-full bg-red-500 mr-1"></div>
          <div className="w-4 h-4 rounded-full bg-yellow-500 mr-1"></div>
          <div className="w-4 h-4 rounded-full bg-green-500 mr-1"></div>
        </div>
        <div className="flex items-center flex-grow justify-center space-x-1">
          <img className="w-5 h-5" src="/images/General/SVG/file.svg" alt="File"/>
          <p className="text-xs font-bold text-white">File.txt</p>
        </div>
      </div>

      <div className="flex-grow bg-[#242424] pt-8 lg:pt-0 overflow-y-auto">
        <p className="text-white text-xs p-2">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora iusto debitis modi hic vitae, neque tempore, ab, molestiae voluptatem minus laboriosam magni laborum. Incidunt fugit cumque amet quia omnis porro.
            Nostrum, reiciendis deserunt. Quod adipisci nostrum aliquid minima quaerat rem aliquam sapiente perspiciatis vel molestiae repellendus explicabo exercitationem, commodi culpa voluptate atque tenetur doloremque incidunt, laudantium, quidem dolor ratione nobis.
            Enim non necessitatibus voluptatem corrupti optio reprehenderit itaque, quibusdam pariatur, quidem veritatis, ratione esse iusto dolore reiciendis quasi quos ex animi fuga! Itaque veniam perspiciatis quisquam deserunt perferendis ea iure!
            Vero, voluptate suscipit. Facere, reprehenderit ut. Delectus maiores minima ipsa magnam sunt odit reiciendis nam cumque! Sapiente, eaque nobis nam vel nostrum dignissimos rem voluptatem quis, incidunt molestiae, sunt expedita!
            Reiciendis accusamus officia minus eum numquam veritatis esse laboriosam sunt natus neque tempora, omnis similique illo consectetur, odio beatae officiis pariatur quo veniam quia itaque ea dolores eius. Odit, amet.
            Necessitatibus et porro perferendis quis. Vero aliquid vitae atque cum maxime, excepturi numquam repellendus ad explicabo eius aliquam rem mollitia omnis veritatis, nam impedit sequi porro autem provident iste assumenda!
            Incidunt recusandae molestias officiis quasi aliquid dicta, commodi id est hic, quisquam fuga rerum voluptates quas repellendus, vel sit minima cumque quibusdam quam! Qui quidem doloribus perferendis vel laboriosam natus.
            Maiores aperiam odit, natus amet fuga incidunt distinctio alias ipsa! Recusandae laborum repellat voluptatum veritatis tempora atque iusto! Aspernatur mollitia ab ipsam beatae unde totam quos provident fugit facilis quibusdam!
            Aliquid quisquam fugiat voluptatem animi, ad totam placeat accusamus quae consequuntur laudantium temporibus vero mollitia modi reiciendis dolorum cumque error ullam veritatis ipsa! Doloremque ipsum cumque ducimus consequatur quo quisquam?
            Dignissimos quos dolores accusamus quibusdam at sunt reiciendis quis optio voluptatem provident et ab, laboriosam error commodi suscipit ipsum, doloremque beatae aspernatur minus quia aliquid iusto sit est. Facere, aliquam.
            Perspiciatis doloribus unde repellendus illo odio eveniet soluta, ea minus. Ab delectus tempore a iure nihil autem eius rem, expedita repellat eveniet ipsam adipisci provident, sunt qui tenetur! Officia, debitis!
            Quo, vel. Consequuntur quas tempora eum. Fugiat facere officiis deleniti quis iste sed ex illum. Excepturi doloribus mollitia quasi, deleniti qui rem culpa eum cum error aut, molestiae repellat sit.
            Quaerat eaque voluptatum nobis reiciendis consectetur debitis ea magni cumque explicabo earum? Hic, exercitationem! Rem tempora labore, accusantium adipisci exercitationem earum incidunt nemo iure sunt officia, provident doloribus temporibus. Veritatis!
            Sapiente possimus rerum error sed. Labore tempore cum veritatis pariatur sequi modi expedita illum id, maiores neque itaque cupiditate odio? Labore repudiandae, aliquid earum nostrum ipsum eligendi amet dolore soluta.
            Asperiores ullam voluptate sed eveniet provident laborum, sint doloribus dicta nobis repudiandae! Quae, voluptatem nesciunt tenetur cum distinctio expedita sed temporibus totam dignissimos, inventore atque rem explicabo hic pariatur ipsam?
            Doloribus dolorum error excepturi, nesciunt deserunt, eum ea provident iste, sequi repellat pariatur ducimus! Fugit, cumque. Fugiat provident est dolorum! Necessitatibus ea quia nulla excepturi adipisci expedita dolorem alias laboriosam.
            Nihil mollitia nobis non aut quidem optio ex in et expedita blanditiis repellat sequi, voluptates, ab, consequatur modi molestiae. Dolores maiores qui, optio reiciendis suscipit vel doloribus tempora temporibus enim.
            Eius, facilis magnam et est cumque soluta, enim delectus illo laudantium commodi blanditiis eveniet sint doloremque officia aliquid, quaerat accusamus recusandae dignissimos pariatur! Voluptatum, fugiat facilis? Labore qui incidunt sunt.
            Illo harum enim praesentium assumenda sequi natus, nisi culpa illum velit eius distinctio molestiae maxime. Autem nobis molestias quis possimus, est ea magni nemo incidunt architecto inventore, dolorem, quos ipsa!
            Rem, vel esse! Iste culpa veritatis quia, error, voluptas laboriosam aut saepe praesentium delectus et provident necessitatibus eaque fugiat minima vitae voluptates maxime facere atque itaque? Corrupti modi quaerat eaque.
            Deserunt perspiciatis rerum saepe ducimus esse ipsum sequi vero, repellendus, odit exercitationem, velit ut adipisci mollitia architecto sint illo quod rem deleniti suscipit corrupti sapiente! Sint ipsam eos eius animi!
            Totam quam quia, nisi tempora quibusdam doloremque est adipisci quis nostrum perspiciatis exercitationem, neque iure excepturi quasi magni fugiat iste harum itaque earum! Molestiae ratione et inventore optio dolores laboriosam!
            Ipsa, alias. Quisquam, excepturi. Deleniti totam vel hic saepe iusto voluptatibus aperiam enim, repellat officia ex, laudantium vero alias, eius iste. Voluptatem, error! Placeat fugit deserunt accusamus totam corporis fuga.
            Dicta soluta minima architecto dignissimos, culpa excepturi facere blanditiis aspernatur similique molestias aliquam laboriosam quidem aliquid beatae labore. Fugiat nam sit eligendi ab sapiente quis tenetur? Minima numquam officia eligendi?
            Cupiditate recusandae quidem rem quaerat neque fuga deserunt, autem repellendus sint aliquid expedita? Vero animi reprehenderit rem voluptatem harum quasi, eos pariatur velit reiciendis! Velit impedit molestiae vel harum earum?
            Animi vel iusto repellat corporis accusamus officia quibusdam quos fuga autem saepe, debitis tempora numquam cumque harum ducimus excepturi repellendus tenetur ex optio! Deleniti, odio vel mollitia quia delectus quam.
            Odit animi, quae qui repudiandae esse recusandae inventore libero aspernatur unde dolores quaerat facilis eveniet provident quo architecto voluptatem aperiam facere quibusdam, ad eaque cupiditate nisi tempora, distinctio nulla. Odit?
            Exercitationem tenetur debitis accusantium fugiat doloribus reprehenderit itaque ut illum aliquam. Placeat fugiat distinctio deleniti nisi. Cupiditate magni consectetur laboriosam nemo cum delectus quo necessitatibus aspernatur, sequi ducimus repellendus distinctio!
            Dicta asperiores magnam eveniet, ipsam amet temporibus repudiandae eius recusandae. Pariatur incidunt beatae debitis, quae ratione a minima ab consequatur quam harum blanditiis, accusantium optio aperiam quisquam illo cum explicabo!
            Odit neque nam sunt iste officia pariatur quos molestiae, vel commodi nulla, hic totam tenetur dicta aliquid sed dolore veniam repudiandae minima impedit voluptate repellat optio! Deleniti nisi nesciunt eos?
            Quidem sit tempora sapiente qui obcaecati laboriosam sint porro autem, nisi veniam optio vitae quo doloremque ipsa rerum aspernatur provident amet facere ut facilis corrupti voluptatibus itaque. Consectetur, nobis libero?
            At exercitationem corrupti totam rerum veniam architecto. Ipsam voluptates delectus excepturi aliquid culpa quas molestias voluptatum expedita quae, quaerat nobis quasi voluptatibus. Illo amet aut perspiciatis voluptatum? Natus, commodi dolorum?
            Minus maxime aliquam vitae. Totam animi, esse quasi commodi, saepe assumenda ea perspiciatis explicabo ipsum, nesciunt laudantium voluptatum voluptates! Repellendus possimus, ipsam reiciendis assumenda voluptas ex sit sed reprehenderit dolore!
            Cupiditate dignissimos eaque, beatae, esse officiis tempore at nam alias magnam quam accusamus quaerat odit culpa earum temporibus repellendus quod! Voluptates sapiente eaque repellendus officiis itaque ex, impedit molestiae assumenda.
            Reiciendis quae, similique illum officia debitis accusamus deleniti optio, doloribus distinctio totam ipsam laudantium dolorem modi voluptatibus eius libero qui necessitatibus illo inventore facere nesciunt. Ex, exercitationem pariatur. Nihil, veritatis?
            Provident quisquam ut illum nisi odit omnis officia nobis laudantium architecto corrupti, atque id at distinctio, quidem perspiciatis ab laboriosam, voluptatibus libero vitae excepturi molestias? Voluptatibus necessitatibus ut autem architecto.
            Sint sunt animi culpa est in, harum maxime similique quo exercitationem voluptas autem corporis, odit eos fugit ipsum ullam iure quaerat unde, ex soluta. Aut totam eius veritatis dignissimos dolorum?
            Minus tempora minima enim distinctio aspernatur aut eius, eum voluptas qui cum et! Ratione, harum nulla nemo unde reiciendis possimus impedit dignissimos, fugiat aut dolorum vero alias tempora eos debitis.
            Natus placeat possimus aperiam eveniet odit eum expedita asperiores sequi temporibus minima dolores est modi unde ad maiores, quisquam cum, ipsam sit, dolor vitae quia esse enim. Nulla, exercitationem dolorem.
            Enim consectetur reprehenderit sequi laborum voluptatem dolores in esse illum officia veritatis nihil aspernatur a, explicabo dignissimos culpa adipisci rerum natus. Non sed iste dolorem distinctio iusto, eligendi vero dignissimos!
            Molestiae consequuntur in delectus placeat nihil nostrum? Repudiandae asperiores blanditiis nam eum molestias sed totam optio ex? Impedit dolore exercitationem aliquid excepturi, id sapiente odio accusantium, facilis pariatur voluptate quos?
            Sequi saepe praesentium, nemo iste recusandae quidem non doloribus illo tenetur unde minus veniam, eum, molestiae accusantium explicabo consectetur voluptatum dolor atque autem veritatis eligendi nulla quae animi? Tempore, consequatur?
            Tenetur esse expedita quasi, dicta ipsam molestiae repellendus autem! Earum eveniet laudantium suscipit quia ullam neque sit aut fugiat fugit tenetur repudiandae, nulla sed iusto nisi, et harum, cumque excepturi.
            Quae, reprehenderit aspernatur qui ullam molestiae dolorum nam, ex, itaque accusamus omnis numquam nihil iusto veniam distinctio sint labore rerum impedit enim deleniti esse quo? Similique modi praesentium vel eius?
            Modi dolorum reiciendis voluptatem laudantium quaerat esse a minus unde! Architecto neque possimus necessitatibus facilis ullam totam dicta reiciendis quae accusamus asperiores voluptatibus aliquam pariatur, facere, odit illo, nesciunt eligendi!
            Sed ducimus tempora voluptas doloremque in est cum molestias, placeat, aliquid ab laboriosam. Rerum optio omnis at cumque in itaque magnam, nihil ratione nobis excepturi similique veritatis libero ex quibusdam.
            Explicabo eaque nesciunt in odit quaerat laudantium aliquam dolores laborum, neque, perspiciatis iure? Alias eveniet recusandae deserunt atque molestiae mollitia officia explicabo at, sed commodi qui ipsam. Delectus, asperiores sunt.
            Reprehenderit, aliquam id. Assumenda, quae dolorum a obcaecati quidem nam ipsam quasi ratione. Repellat nulla dolores rem cum? Obcaecati animi nisi eos dicta quidem, officiis pariatur expedita cum non rem.
            Ex vitae labore odio minima cupiditate, esse quod magni et sapiente. Eveniet voluptates rem, iste quos quo eaque maiores velit ratione quis. Expedita iure provident corporis dolorem, atque aperiam beatae?
            Iure voluptas dignissimos ducimus ipsa quasi provident in amet reprehenderit. Animi, libero culpa necessitatibus doloremque assumenda perspiciatis veniam dicta soluta voluptatibus in distinctio minima, quos maiores voluptates doloribus non ipsam.
            Iure nihil, debitis quas corporis architecto nulla, inventore vero a neque sapiente quis nostrum at autem. Repudiandae voluptate vero labore soluta! Atque fugit aspernatur in maxime nostrum asperiores, porro et.
            Neque fuga eos, nesciunt odit unde optio iste pariatur, dolores nisi, eum laudantium! Officiis placeat qui error aperiam, accusamus ipsum veritatis nemo aut. Officia, repellat suscipit! Quae voluptatem modi aut!
            Nam praesentium quo excepturi saepe perspiciatis ullam et, aut fuga officiis quod nesciunt ex ipsum impedit iste dolorum dignissimos minima. Quas error tenetur aspernatur laboriosam blanditiis deleniti minima totam repellendus?
            Odit unde enim facilis dolores quisquam repellat perspiciatis explicabo, blanditiis fugit! Quos voluptatem beatae, exercitationem suscipit eveniet ut in veniam ex reprehenderit blanditiis. Eius sed itaque, atque totam nam ab.
            In nostrum, ullam natus quisquam repellat exercitationem sunt labore iusto voluptatem commodi cumque doloremque cum inventore rerum nisi quia blanditiis. Ducimus distinctio adipisci aut vel provident dicta alias quidem architecto?
            Alias, mollitia id aliquid, rerum iusto animi eveniet quibusdam et cumque neque maiores recusandae corrupti. Modi similique rem eaque illum aut eius voluptas cupiditate excepturi facere beatae. Dolorem, nostrum impedit?
            Laboriosam veniam iste, tempore minus incidunt cum molestiae voluptatum distinctio ex beatae ipsum maxime, odio tempora velit ea nesciunt optio perferendis dolorum rem commodi unde doloribus culpa quas nisi? Aliquam?
            Earum nesciunt enim asperiores illo, temporibus explicabo dolores voluptate delectus atque libero iusto mollitia a minus, quis eius, nisi incidunt! Aspernatur harum voluptas similique beatae ipsa in ratione est vero.
            Iste, ad? Culpa, similique officiis! Impedit recusandae accusamus blanditiis. Officiis deleniti accusantium culpa pariatur unde architecto porro. Velit debitis sunt voluptatum et magnam sapiente architecto, deleniti voluptates, atque, libero dicta.
            Quae illo alias temporibus iste repellat maiores totam ex nulla, molestiae aperiam maxime consectetur id est, quis aut repudiandae debitis dolorem, ratione deleniti nihil corrupti nam eum tempore? Saepe, ipsa!
            Nesciunt assumenda blanditiis velit voluptate optio pariatur dolorem ex ullam porro eaque odit dolor repudiandae error, excepturi, a vel, voluptatum voluptates consectetur! Cupiditate veritatis adipisci dolorum quam deleniti vel quia.
            Et aliquam quisquam dolore, cupiditate eaque accusamus rerum quo fugit. Voluptatum magnam quam at minima sit animi? A quod non corporis, blanditiis, aperiam atque voluptatum odio necessitatibus voluptatibus earum voluptatem.
            Nesciunt optio non eaque deserunt, ipsam, magni corrupti eos placeat minima neque vel quaerat atque, ad necessitatibus debitis ea sequi esse beatae at fugiat quae? Explicabo unde hic veniam nesciunt.
            Commodi praesentium ab quam sit quos quod sed, mollitia veniam sint, facere aliquam enim rem dignissimos earum eum quae? Mollitia, soluta ipsam omnis quos quo ducimus quod consequatur culpa aut.
            Possimus officia, repudiandae, maxime aut consectetur unde molestias quos, excepturi aspernatur suscipit numquam culpa. Iste, impedit. Accusamus debitis, voluptas numquam sint, nulla quidem ratione odio, architecto tenetur pariatur doloremque nesciunt.
            Tempore repudiandae veritatis, et, quibusdam ex ea assumenda officiis ipsam consectetur ratione iste fuga cupiditate, facere rerum ipsum dolorem distinctio quia. Quos aliquid est beatae, libero officia commodi architecto quidem.
            Perferendis consequatur fugiat, dolorum natus eligendi iure recusandae? Voluptatum itaque eaque unde deserunt doloribus fugit porro, quisquam harum, repellendus est qui dolore eveniet tempore corporis libero maxime aperiam ut atque.
            Nobis suscipit rem magnam harum expedita labore. Quibusdam facilis nobis molestias reiciendis qui deserunt, earum cupiditate dolores optio libero mollitia omnis excepturi labore quas debitis eum laudantium saepe fugiat ipsam!
            Doloribus vitae pariatur repellat dolorum? Delectus, provident labore quisquam dolorem eius sed, sint architecto cumque, iusto dolores distinctio. Iste iusto dicta neque aliquid nisi. Commodi, dolor. Libero sint neque ducimus.
            Doloribus corrupti architecto sed neque, placeat et a numquam tempore accusamus vero eius ex similique maiores! Inventore quibusdam cum, laboriosam repellat incidunt neque expedita reiciendis velit autem iusto ducimus accusamus?
            Illum aspernatur distinctio cumque deleniti quisquam, vitae odit est earum eaque pariatur quos? Ipsam blanditiis, error quisquam est quaerat itaque impedit totam nemo modi, hic deleniti, quasi accusamus cum illum.
            Doloribus deserunt odit, aliquid dolor reprehenderit necessitatibus nisi veritatis, laborum voluptatum iste atque animi neque quaerat dolore error quas ullam, perspiciatis earum! Culpa natus aperiam ut blanditiis sequi aliquam et.
            Harum blanditiis nostrum nobis dolorum expedita eligendi commodi, perspiciatis a inventore atque dolorem quaerat id nihil. Aliquam eligendi, nostrum voluptatibus quo a fugiat illum debitis molestias accusantium veritatis, repellat incidunt.
            Assumenda doloribus eum tenetur tempore mollitia voluptate corporis molestias? Et non impedit est consequuntur ipsa quia tenetur autem esse, quo hic quidem laudantium beatae. At exercitationem aliquid voluptates accusantium nisi.
            Repellat explicabo sapiente reiciendis, quos beatae expedita iste blanditiis dolorum modi reprehenderit culpa debitis officiis nam rem! Exercitationem laudantium delectus vero blanditiis cupiditate fugiat est, quam fugit eligendi, quisquam nihil!
            Autem aspernatur doloribus expedita perferendis consequuntur perspiciatis facere id nostrum totam libero dolor saepe, molestias animi earum debitis quis voluptates nulla explicabo esse, provident ducimus nemo. Officia architecto excepturi totam.
            Autem perferendis incidunt eius neque mollitia. Qui id temporibus facilis corrupti aut impedit sunt repellendus ad, placeat voluptates corporis fuga, sapiente deleniti, possimus quam? Quas, recusandae laudantium. Eum, officiis ea?
            Minus ipsam repellendus nostrum? Animi eligendi a minus cum necessitatibus modi provident recusandae magni exercitationem officia nostrum sit quos, nemo autem. Natus voluptatibus reprehenderit praesentium sit quas dicta quaerat facere!
            Aspernatur aperiam sunt pariatur repellendus exercitationem animi doloribus voluptatem corporis magni officiis, eos velit perspiciatis unde quas explicabo vitae impedit, eveniet in excepturi minima voluptatibus quod blanditiis accusantium. Nisi, non.
            Minima aperiam corporis, dolores voluptatem pariatur aspernatur delectus eaque totam sint officia ex deserunt illo! Quod illo corporis voluptate soluta consequuntur quisquam earum quasi, quae dolore, cupiditate exercitationem ipsa ex.
            Maxime voluptate, quasi impedit delectus dolorum ducimus magni consequuntur suscipit rem minus deleniti! Nam nisi, maiores deserunt laudantium mollitia, harum tempora veniam nostrum id libero earum itaque cum ut inventore.
            Voluptate distinctio similique, aliquid accusantium quo laboriosam omnis cum, quod voluptatum saepe velit quas quaerat, soluta quisquam vero dolorem molestias. Saepe maiores ratione aut consequuntur deleniti exercitationem, qui facilis. Qui?
            Saepe fugiat itaque animi laudantium fuga. Quidem vitae porro dolorum quam explicabo, architecto neque quibusdam quos aperiam laboriosam commodi eum non provident, omnis unde accusamus qui saepe blanditiis, maxime repellat!
            Minus ab architecto id ut nisi dolore. Vero, labore possimus! Autem, quia. Nostrum nihil excepturi sunt est aspernatur debitis dignissimos. Earum sunt ipsa facere deserunt dolores pariatur aperiam magni velit?
            Molestias reiciendis alias sed distinctio aut rem fugit optio deserunt accusamus ad voluptatum velit aperiam iure, minus beatae rerum, architecto in hic deleniti maiores! Ipsam porro modi quaerat rem maxime.
            Veritatis repellat, labore mollitia natus iste, obcaecati, nostrum maxime quibusdam iusto necessitatibus ratione dicta. Optio animi corporis laboriosam eum aperiam, sed, iste dolorum ducimus dolor cumque officiis odio assumenda ipsam?
            Est omnis eos quis, aliquid dicta culpa officiis, accusamus consequatur commodi enim dolore eius distinctio, eum magnam fuga sequi sed delectus dolor ratione blanditiis voluptatibus! Quos, debitis corrupti. Non, laudantium?
            Nemo similique doloremque nisi in soluta et esse numquam nulla labore aspernatur vero dolorem harum rerum quasi, amet ipsum dignissimos omnis quaerat laudantium consequatur fuga dolore mollitia natus optio! Suscipit?
            Veniam unde optio sint non reiciendis temporibus praesentium ipsam cupiditate obcaecati corporis perspiciatis, culpa eius possimus quidem officiis accusantium similique illo dolorem fugit sapiente. Culpa laborum excepturi eaque possimus adipisci!
            Voluptatem nulla, ratione ducimus, sint, ipsum reprehenderit non cumque ullam laborum voluptatum recusandae corrupti nesciunt deserunt saepe? Atque, repudiandae? Dignissimos cupiditate quis, fugiat numquam quaerat reiciendis earum. Ex, consequuntur amet?
            Sunt consequuntur iusto provident delectus praesentium? Iste aut asperiores excepturi amet maxime molestias illum reprehenderit saepe quisquam fuga minima, laborum repudiandae modi ullam pariatur optio ea in, eius, atque quis.
            Voluptate sequi quis eos repudiandae, cupiditate doloribus aspernatur necessitatibus consequuntur tenetur temporibus exercitationem reprehenderit! Iusto officia, voluptates ipsa perspiciatis quod sed. Incidunt neque perspiciatis nam minus voluptatibus illum nobis ab!
            Fuga numquam qui, dicta harum a officia nisi alias hic asperiores nobis officiis, possimus pariatur voluptates nam nemo magni neque expedita iusto, laborum veritatis optio at nihil laboriosam. Eligendi, saepe!
            Cum suscipit voluptas perferendis, aspernatur ab optio nostrum tempore quod in sit aliquid nobis iste accusamus hic velit veniam. Quia officiis molestiae aliquid illum alias labore, nesciunt est accusantium ex!
            Fugiat natus reiciendis nostrum labore. Fugiat neque dicta deserunt quos amet consequuntur magnam, voluptatum reprehenderit id accusantium adipisci iste, ratione aliquam cum? Impedit eligendi vel quo saepe illum id expedita?
            Repellat nostrum vitae sequi voluptas velit quas pariatur nam ea eveniet neque. Harum nemo totam quis accusamus unde vero ab consequuntur cupiditate ad. Eius doloribus officia ipsa harum, ratione suscipit?
            Sapiente accusantium commodi quo neque dolores ipsam minima culpa fuga ut ullam harum possimus, assumenda excepturi? Nihil vero dolor rem quis et unde corporis reiciendis velit. Dolore provident aperiam qui.
            At architecto voluptate libero perspiciatis ad. Veniam magnam ducimus officiis ipsum ut, natus repellat error. Ea vitae adipisci, praesentium amet reiciendis veniam officiis, corrupti, a ullam ipsa repellendus illo blanditiis.
            Earum consectetur ipsa voluptatum ullam placeat reiciendis repellat voluptatibus. Soluta eaque a obcaecati explicabo, reprehenderit pariatur veniam consequatur vel sunt, cumque laudantium velit doloremque, vitae ullam quidem labore aut quo!
            Ipsam minima quidem totam placeat omnis quia assumenda accusantium, expedita cupiditate commodi, dolorum deserunt voluptatum, tempore nihil incidunt esse reprehenderit magnam provident eaque dicta optio numquam iste. Exercitationem, accusantium ullam?
          </p>
      </div>

      <div className="hidden lg:flex justify-between items-center p-4 bg-[#242424] rounded-br-lg rounded-bl-lg border-t-[0.5px] border-gray-600 bg-[#3F3837]"></div>
    </div>
  );
}
